
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

logging:
  level:
    com.github.hyeyoom.blog: trace
    org.springframework.cache: trace