spring:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:inmemdb

logging:
  level:
    com.github.hyeyoom.blog: trace
    org.springframework.cache: trace