
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      path: /db
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/h2_db;AUTO_SERVER=TRUE
    username: devlog-dba
    password: ${DB_PASSWORD}
